schema_version: 1

context:
  name: azure-mgmt-cognitiveservices
  version: 13.6.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure_mgmt_cognitiveservices-${{ version }}.tar.gz
  sha256: 612e56f79e824f81d590cff0c09253358ada065d5a6169c13905fc35064d9b40

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - isodate >=0.6.1
    - typing_extensions >=4.6.0
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2

tests:
  - python:
      imports:
        - azure.mgmt.cognitiveservices
        - azure.mgmt.cognitiveservices.aio
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Cognitive Services Management Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
